- _helpers/dev/cli.mts
- _helpers/src/cluster.ts
- _helpers/src/pepr.ts
- hello-pepr-reconcile/capabilities/reconcile.e2e.test.ts
This adds the ability to inject a custom image into the clusters which allows us to run the tests from Pepr Core against a development image.
Usage:
```plaintext
npm run test:e2e -- -i pepr:dev
```
> add image flag to be able to inject a specific image into the tests/clusters

- _helpers/src/pepr.ts
Relates #63 
Adds a more explicit error message when log parsing with the `sift()` helper runs into a non-JSON line in the log stream.
> chore: catch & log errors during log sift()

- _helpers/src/pepr.ts
Does not attempt to parse around deprecations.
The sift command is creating errors in our CI when the deprecation is being parse. I want to filter those lines before the parse.
```json
'(node:1) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.',
'(Use `node --trace-deprecation ...` to show where the warning was created)',
```
[Link](https://github.com/defenseunicorns/pepr/actions/runs/10800262187/job/29957921369)
> chore: no parse options

- test-specific-version/capabilities/versions.e2e.test.ts
This PR accounts for dependabot upgrades to package.json files by reading the pepr version from package.json during E2E version tests.
> fix(testing): derive pepr version from package.json in test

- .github/workflows/devDeps.yml
Follow on work to use the new devDependency update helper ( created in this [PR](https://github.com/defenseunicorns/pepr-excellent-examples/pull/152) ) in a job on CI.
Desire is for a scheduled (nightly) job to submit a PR to update the excellent examples modules' devDependencies -- similar to the way dependabot is suggesting updates via PR to the regular deps.
> chore: update pepr-excellent-examples examples' devDependencies from CI workflow

- _helpers/src/pepr.ts
- package.json
I noticed a mismatch between reported pepr versions in the test logs. This PR fixes that mismatch.
Note how the example below reports `0.37.2` and `0.36.0` as in use during the same test run.
Example:
```
❯ npm run test:e2e -w hello-pepr-store
[...]
Pepr Version under test: 0.37.2
Pepr Image under test: sha256:deba991c2df63ab0099de55f5440703d2d17d6ebe635595badf0bc7d04715cbe [pepr:dev]
[...]
console.time
pepr@0.36.0 ready (total time): 32814 ms
at moduleUp (../_helpers/src/pepr.ts:133:11)
```
> Display accurate version of pepr in test logs

- _helpers/src/Cmd.ts
- _helpers/src/pepr.ts
- hello-pepr-finalize/capabilities/finalize.e2e.test.ts
- hello-pepr-finalize/capabilities/finalize.ts
- hello-pepr-finalize/capabilities/scenario.update.opt-out.yaml
Adds ability for Module Author to "opt out" of removing Pepr's metadata.finalizers entry.
Relates [#1316 ](https://github.com/defenseunicorns/pepr/issues/1316)
> feat: add ability to exit Finalize() callback WITHOUT removing the finalizer 

- _helpers/dev/cli.mts
- _helpers/src/pepr.e2e.test.ts
- _helpers/src/pepr.ts
When running E2E tests, I noticed that a log message displayed a semVer version instead of the local pepr build under test. This PR fixes that logging issue by updating calls to `peprVersion()`.
It also uses the `--detectOpenHandles` flag instead of `--runInBand` flag from jest. This flag implies `--runInBand`. CLI docs [here](https://jestjs.io/docs/cli).
> Display correct pepr version under test when logging version

- hello-pepr-store/capabilities/store.ts
- renovate.json
Double set and remove item and wait to make sure we cover the use-case for when there is a non-change,  keeping the store idempotent
> chore: double set/remove and wait

- hello-pepr-store/capabilities/store.ts
do not try to remove an item that does not exist bc Kubernetes will not let you
> chore: do not try to remove something that is not there

- .github/workflows/devDeps.yml
Update job is failing in CI _when no updates are required_.
This is happening because of a call to `return` (which _would_ be fine if this logic was being run in a function, but it's not) from the top-level scope of the CI script.
This PR just swaps an invocation of `exit 0` in where the early return is required.
> test: fix silly early-return syntax mistake

- _helpers/src/pepr.ts
Adding a new failure-handler case to the pepr logs helper to expose full error message for error we're seeing over in Pepr CI:
Relates to https://github.com/defenseunicorns/pepr/pull/1676
> chore: add new failure message case

- _helpers/src/pepr.ts
Helps pepr's e2e test logs helper not choke on warnings like this:
Relates to https://github.com/defenseunicorns/pepr/pull/1676
> test: suppress ExperimentalWarning: messages in logs helper

- _helpers/src/cluster.ts
When running the e2es in CI, the cleanup helper's Delete calls are being throttled by the kubeapi server (which is causing the tests to fail) -- this PR adds some error handling surrounding that case & inserts some retry logic in an attempt to course correct.
Relates to https://github.com/defenseunicorns/pepr/issues/1709
> test: add retries to cluster test data cleanup helper

- package-lock.json
- test-specific-version/package.json
PEXEX test-specific-version is failing constantly affecting CI. We need to update the Pepr dependency in order to pass CI and unblock pipelines.
> Test specific version fix

- hello-pepr-generic-kind/.eslintrc.json
- hello-pepr-generic-kind/.gitignore
- hello-pepr-generic-kind/README.md
- hello-pepr-generic-kind/capabilities/genericKind.e2e.test.ts
- hello-pepr-generic-kind/capabilities/genericKind.ts
- hello-pepr-generic-kind/capabilities/scenario.create-or-update.yaml
- hello-pepr-generic-kind/capabilities/scenario.create.yaml
- hello-pepr-generic-kind/capabilities/scenario.delete.yaml
- hello-pepr-generic-kind/capabilities/scenario.setup.yaml
- hello-pepr-generic-kind/capabilities/scenario.update.yaml
- hello-pepr-generic-kind/jest.config.json
- hello-pepr-generic-kind/package.json
- hello-pepr-generic-kind/pepr.ts
- hello-pepr-generic-kind/tsconfig.json
- package-lock.json
- package.json
Ensures that generic kinds go through admission and be watched over all events.
> chore: generic-kind e2e

- hello-pepr-generic-kind/package.json
- package-lock.json
For some reason the pepr depedency in `hello-pepr-generic-kind` was using the `npm pack` version of Pepr
> chore: fix package.json in hello-pepr-generic-kind

- hello-pepr-load/package.json
The load test has not passed in 3 weeks. This is because the dev dependencies were updated on all projects other than the load test. We are not able to install Pepr due to this difference. 
https://github.com/defenseunicorns/pepr/actions/runs/13550823353/job/37873752935#step:15:71
```bash
Install package artifact into working directory module
{
"cmd": "npm install pepr-0.0.0-development.tgz",
"cwd": "/tmp/load.cli.ts-M1fyZG"
}
{
stdout: [],
stderr: [
'npm error code ERESOLVE',
'npm error ERESOLVE unable to resolve dependency tree',
'npm error',
'npm error While resolving: hello-pepr-load@0.0.1',
'npm error Found: typescript@5.3.3',
'npm error node_modules/typescript',
'npm error   dev typescript@"5.3.3" from the root project',
'npm error   peer typescript@">=4.8.4 <5.8.0" from …
```
> chore: load-test ts version is incorrect

- package-lock.json
- package.json
Remove eslint deps as Pepr started using a lower eslint version
> chore: downgrade eslint for now

- _helpers/dev/cli.mts
if you pass a custom package flag, the e2e's were not actually using that version of Pepr, they were using the top level version. With this PR, if you pass in `--custom-package` flag, then it installs it at the root which allows the modules to use it.
> chore: install custom package at root

- pepr-operator/webapp-dark-es.yaml
- pepr-operator/webapp-light-en.yaml
This PR stores webapp specs as yaml files for easy modification in the future and to support `diff` in the operator tutorial.
> chore: store webapp specs as yaml files

- hello-pepr-alias/capabilities/alias.e2e.test.ts
- hello-pepr-config-ignored-controller-ns/capabilities/ignored-ns.e2e.test.ts
- hello-pepr-config-ignored-ns/capabilities/ignored-ns.e2e.test.ts
- hello-pepr-config/capabilities/config.e2e.test.ts
- hello-pepr-deletion-timestamp/capabilities/deletion.e2e.test.ts
- hello-pepr-finalize/capabilities/finalize.e2e.test.ts
- hello-pepr-generic-kind/capabilities/genericKind.e2e.test.ts
- hello-pepr-hooks/capabilities/hooks.e2e.test.ts
- hello-pepr-mutate/capabilities/mutate.e2e.test.ts
- hello-pepr-ns-all/capabilities/namespace.e2e.test.ts
- hello-pepr-ns-bounded/capabilities/namespace.e2e.test.ts
- hello-pepr-onschedule/capabilities/onschedule.e2e.test.ts
- hello-pepr-reconcile-global/capabilities/reconcile.e2e.test.ts
- hello-pepr-reconcile-kind/capabilities/reconcile.e2e.test.ts
- hello-pepr-reconcile-kindns/capabilities/reconcile.e2e.test.ts
- hello-pepr-reconcile-kindnsname/capabilities/reconcile.e2e.test.ts
- hello-pepr-regex-name/capabilities/regex-name.e2e.test.ts
- hello-pepr-regex-ns-all/capabilities/namespace.e2e.test.ts
- hello-pepr-regex-ns-bounded/capabilities/namespace.e2e.test.ts
- hello-pepr-store-redact-logs/capabilities/store.e2e.test.ts
- hello-pepr-store-resources/capabilities/store.e2e.test.ts
- hello-pepr-store/capabilities/store.e2e.test.ts
- hello-pepr-validate/capabilities/validate.e2e.test.ts
- hello-pepr-warnings/capabilities/warnings.e2e.test.ts
- hello-pepr-watch/capabilities/watch.e2e.test.ts
We have been hitting timeouts in the runners. It seems more frequently right now that the whole module is not coming up as the webhook is not reachable by Kubernetes. If we increase the initial limit around actually deploying the webhook those pods are more likely to be up and healthy and the theory is we will get less flakes.
> chore: increase moduleUp timelimit

- test-specific-version/package.json
This PR fixes a missed version bump following the ESlint migration in #294
> fix: update version in missed test case

- _helpers/dev/cli.mts
fixes #312 
Since switching to ESLint v9.x we had to update dependencies in Pepr. We also had to change logic in PEXEX to install the nightly version of pepr as seen in this [PR](https://github.com/defenseunicorns/pepr-excellent-examples/pull/307/files). Before we were installing npm i pepr, and seeing check if the pepr env is pepr. Now we are installing pepr@nightly which makes this check never return positive getPeprAlias() !== 'pepr'. We need to change that to .StartsWith("pepr")` so we can return true for a nightly and also we need to force install the dependencies since there are some clashes due to newer versions of dependencies in the nightly.
> chore: update pepr installation and check

- _helpers/dev/cli.mts
https://github.com/defenseunicorns/kubernetes-fluent-client/issues/675
KFC cannot install updates, it is choking on the `restoreBackup()`. During the backup restore this now restores the original package*.json
This also uses the standard CI env var for github actions CI
https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/store-information-in-variables#default-environment-variables
> chore: install after backup

- _helpers/src/pepr.ts
In support of #338, we need to use the nightly release of Pepr until the functionality provided by https://github.com/defenseunicorns/pepr/pull/2359 is in a released version of Pepr.
> fix: Use nightly release in PEXEX

- _helpers/src/pepr.ts
This PR uses `--yes` in support of https://github.com/defenseunicorns/pepr/pull/2382. It must be brought in along with that PR.
> fix: use --yes in pepr deploy

- hello-pepr-config/capabilities/config.e2e.test.ts
- hello-pepr-watch/capabilities/watch.e2e.test.ts
Im support of Pepr PR #[2359](https://github.com/defenseunicorns/pepr/pull/2359) these two new test cases ensure that only admission resources are deploy if the bindings are all admission, and likewise that only watcher resources are deployed for only watches.
This PR requires #337 to be merged in first as the `moduleUp` command is assuming that both controllers will be deployed which is no longer accurate, only the required controllers
> chore: e2e tests for 2359

- _helpers/src/pepr.ts
In support of https://github.com/defenseunicorns/pepr/pull/2494
- remove emoji logs so timeout does not occur
- runs `npx pepr deploy` with `LOG_LEVEL=debug`
```bash
> npm run test:e2e -w hello-pepr-store -- --image pepr:dev --custom-package pepr-0.0.0-development.tgz
✓ capabilities/store.e2e.test.ts (5 tests) 84847ms
✓ store.ts (5)
✓ module default store (5)
✓ data injection (2)
✓ can insert in onReady hook 1ms
✓ can clear in onReady hook 0ms
✓ asynchronous interaction (1)
✓ key can be written, read, and removed 1ms
✓ synchronous interaction (1)
✓ key can be written, read, and removed 0ms
✓ observed interaction (1)
✓ sees batched update 1ms
Test Files  1 passed (1)
Tests  5 passed (5)
Start at  14:48:53
```
> Pexex in debug mode
