pepr-operator/README.md
pepr-operator/capabilities/index.ts

More sophisticated reconcile mechanism and updates to docs

More sophisticated reconcile mechanism and updates to docs

---

pepr-operator/package.json

Update the version of Pepr Operator

chore: update pepr operator

---

hello-pepr-onschedule/capabilities/onschedule.e2e.test.ts
hello-pepr-onschedule/capabilities/onschedule.ts

Created this PR for Barrett and we reviewed it as a team

fix: avoid timing failures on CI

---

hello-pepr-store/capabilities/store.e2e.test.ts
hello-pepr-store/capabilities/store.ts

Store seems to be fixed now from a passed PR where we cleared the store on failure.

chore: uncomment store

---

hello-pepr-store/capabilities/store.ts

e2e test for https://github.com/defenseunicorns/pepr/pull/1182

chore: ensure store.clear() does not blow up

---

_helpers/dev/cli.mts
_helpers/src/TestRunCfg.ts
_helpers/src/general.ts
_helpers/src/pepr.ts
_helpers/src/pepr.unit.test.ts

Dump unparseable log lines, specifically.   Fixes #https://github.com/defenseunicorns/pepr/issues/1197.

test: output unparsable log lines on failure

---

package-lock.json

for some reason the lock file is missing after PRs sometimes

chore: add lock

---

hello-pepr-custom-rbac/package.json
package-lock.json

fixes pepr version in custom rbac e2e

chore: fix pepr version in custom rbac

---

hello-pepr-load/README.md

Fixes a typo in the hello-pepr-load module's README.md.

fix: readme instruction

---

_helpers/src/cluster.ts

Reverts defenseunicorns/pepr-excellent-examples#222

Revert "test: add retries to cluster test data cleanup helper"

---

package-lock.json
test-specific-version/capabilities/versions.e2e.test.ts
test-specific-version/package.json

no pepr command found, need to install at given version

chore: version needs to install pepr at version

---

hello-pepr-hooks/pepr.ts

chore: update location of admissionrequest

---

.github/workflows/devDeps.yml

add errorBehavior so module is build.
Error can be seen on this [line](https://github.com/defenseunicorns/pepr-excellent-examples/actions/runs/14450654203/job/40522266204#step:9:430)

chore: update error behavior so module is built

---

.github/workflows/devDeps.yml

Dep updates fix 2

---

pepr-operator/capabilities/index.ts
pepr-operator/capabilities/reconciler.ts

Pepr had some changes since this example was written. This PR fixes some build errors.

chore: update old example code

---

_helpers/dev/cli.mts

Adds a flag to use a custom KFC package for testing against a KFC release candidate

chore: command for kfc

---

package-lock.json
test-specific-version/package.json

Hotfix test version

---

_helpers/dev/cli.mts
_helpers/src/pepr.ts

chore: use latest pepr instead of nightly

---

_helpers/dev/cli.mts

This PR arose during a pairing session with @cmwylie19

chore: remove unused code from helpers

---

hello-pepr-store-resources/capabilities/nonmigrated-peprstore.yaml
hello-pepr-store/capabilities/store.e2e.test.ts

Fixes the tests by not assuming all controllers will be deployed and updating the stub peprstore resource

chore: fix tests

---

_helpers/src/pepr.ts

fix: use --yes in pepr deploy command

---

hello-pepr-generic-kind/capabilities/genericKind.e2e.test.ts
hello-pepr-generic-kind/capabilities/genericKind.ts
hello-pepr-generic-kind/package.json

chore: additinional webhooks
